#include "core/item_db.h"

namespace core {

const ItemDef kItemTable[kItemCount] = {
    /* kItemNone           */ {"None", ItemCategory::Tool, 0},
    /* kItemAxe            */ {"Axe", ItemCategory::Tool, 1},
    /* kItemPickaxe        */ {"Pickaxe", ItemCategory::Tool, 1},
    /* kItemHammer         */ {"Hammer", ItemCategory::Tool, 1},
    /* kItemWateringCan    */ {"Watering Can", ItemCategory::Tool, 1},
    /* kItemWateringCanFull*/ {"Watering Can (Full)", ItemCategory::Tool, 1},
    /* kItemFishingRod     */ {"Fishing Rod", ItemCategory::Tool, 1},
    /* kItemWheatSeed      */ {"Wheat Seed", ItemCategory::Seed, 99},
    /* kItemWheat          */ {"Wheat", ItemCategory::Crop, 99},
    /* kItemTurnipSeed     */ {"Turnip Seed", ItemCategory::Seed, 99},
    /* kItemTurnip         */ {"Turnip", ItemCategory::Crop, 99},
    /* kItemCarrotSeed     */ {"Carrot Seed", ItemCategory::Seed, 99},
    /* kItemCarrot         */ {"Carrot", ItemCategory::Crop, 99},
    /* kItemTomatoSeed     */ {"Tomato Seed", ItemCategory::Seed, 99},
    /* kItemTomato         */ {"Tomato", ItemCategory::Crop, 99},
    /* kItemPumpkinSeed    */ {"Pumpkin Seed", ItemCategory::Seed, 99},
    /* kItemPumpkin        */ {"Pumpkin", ItemCategory::Crop, 99},
    /* kItemWood           */ {"Wood", ItemCategory::Material, 99},
    /* kItemStone          */ {"Stone", ItemCategory::Material, 99},
    /* kItemOre            */ {"Ore", ItemCategory::Material, 99},
    /* kItemSapling        */ {"Sapling", ItemCategory::Material, 99},
    /* kItemBerries        */ {"Berries", ItemCategory::Material, 99},
    /* kItemMushroom       */ {"Mushroom", ItemCategory::Material, 99},
    /* kItemHay            */ {"Hay", ItemCategory::Material, 99},
    /* kItemApple          */ {"Apple", ItemCategory::Material, 99},
    /* kItemEgg            */ {"Egg", ItemCategory::Material, 99},
    /* kItemMilk           */ {"Milk", ItemCategory::Material, 99},
    /* kItemHoney          */ {"Honey", ItemCategory::Material, 99},
    /* kItemFishSmall      */ {"Minnow", ItemCategory::Material, 99},
    /* kItemFishMed        */ {"Perch", ItemCategory::Material, 99},
    /* kItemFishBig        */ {"Lunker", ItemCategory::Material, 99},
    /* kItemFence          */ {"Fence", ItemCategory::Placeable, 99},
    /* kItemGate           */ {"Gate (Left)", ItemCategory::Placeable, 99},
    /* kItemPath           */ {"Stone Path", ItemCategory::Placeable, 99},
    /* kItemBridge         */ {"Bridge", ItemCategory::Placeable, 99},
    /* kItemCamp           */ {"Camp", ItemCategory::Placeable, 9},
    /* kItemCoop           */ {"Coop", ItemCategory::Placeable, 9},
    /* kItemBarn           */ {"Barn", ItemCategory::Placeable, 9},
    /* kItemChest          */ {"Chest", ItemCategory::Placeable, 9},
    /* kItemWell           */ {"Well", ItemCategory::Placeable, 9},
    /* kItemBeehive        */ {"Beehive", ItemCategory::Placeable, 9},
    /* kItemCampfire       */ {"Campfire", ItemCategory::Placeable, 99},
    /* kItemLamp           */ {"Lamp", ItemCategory::Placeable, 99},
    /* kItemChair          */ {"Chair", ItemCategory::Placeable, 99},
    /* kItemRug            */ {"Rug", ItemCategory::Placeable, 99},
    /* kItemSign           */ {"Sign", ItemCategory::Placeable, 99},
    /* kItemMailbox        */ {"Mailbox", ItemCategory::Placeable, 99},
    /* kItemWall           */ {"Wall", ItemCategory::Placeable, 99},
    /* kItemFloor          */ {"Floor", ItemCategory::Placeable, 99},
    /* kItemDoor           */ {"Door", ItemCategory::Placeable, 99},
    /* kItemXmasTree       */ {"Xmas Tree", ItemCategory::Placeable, 9},
    /* kItemCoal           */ {"Coal", ItemCategory::Material, 99},
    /* kItemRuby           */ {"Ruby", ItemCategory::Material, 99},
    /* kItemDiamond        */ {"Diamond", ItemCategory::Material, 99},
    /* kItemEmerald        */ {"Emerald", ItemCategory::Material, 99},
    /* kItemAmethyst       */ {"Amethyst", ItemCategory::Material, 99},
    /* kItemPotion         */ {"Potion", ItemCategory::Material, 99},
    /* kItemMineShaft      */ {"Mine Shaft", ItemCategory::Placeable, 9},
    /* kItemOrange         */ {"Orange", ItemCategory::Material, 99},
    /* kItemPear           */ {"Pear", ItemCategory::Material, 99},
    /* kItemPeach          */ {"Peach", ItemCategory::Material, 99},
    /* kItemCauliflowerSeed*/ {"Cauliflower Seed", ItemCategory::Seed, 99},
    /* kItemCauliflower    */ {"Cauliflower", ItemCategory::Crop, 99},
    /* kItemEggplantSeed   */ {"Eggplant Seed", ItemCategory::Seed, 99},
    /* kItemEggplant       */ {"Eggplant", ItemCategory::Crop, 99},
    /* kItemLettuceSeed    */ {"Lettuce Seed", ItemCategory::Seed, 99},
    /* kItemLettuce        */ {"Lettuce", ItemCategory::Crop, 99},
    /* kItemRadishSeed     */ {"Radish Seed", ItemCategory::Seed, 99},
    /* kItemRadish         */ {"Radish", ItemCategory::Crop, 99},
    /* kItemBeetrootSeed   */ {"Beetroot Seed", ItemCategory::Seed, 99},
    /* kItemBeetroot       */ {"Beetroot", ItemCategory::Crop, 99},
    /* kItemStarfruitSeed  */ {"Starfruit Seed", ItemCategory::Seed, 99},
    /* kItemStarfruit      */ {"Starfruit", ItemCategory::Crop, 99},
    /* kItemCucumberSeed   */ {"Cucumber Seed", ItemCategory::Seed, 99},
    /* kItemCucumber       */ {"Cucumber", ItemCategory::Crop, 99},
    /* kItemCornSeed       */ {"Corn Seed", ItemCategory::Seed, 99},
    /* kItemCorn           */ {"Corn", ItemCategory::Crop, 99},
    /* kItemShrimp         */ {"Shrimp", ItemCategory::Material, 99},
    /* kItemClownfish      */ {"Clownfish", ItemCategory::Material, 99},
    /* kItemSnail          */ {"Sea Snail", ItemCategory::Material, 99},
    /* kItemCrab           */ {"Crab", ItemCategory::Material, 99},
    /* kItemSeahorse       */ {"Seahorse", ItemCategory::Material, 99},
    /* kItemOctopus        */ {"Octopus", ItemCategory::Material, 99},
    /* kItemLobster        */ {"Lobster", ItemCategory::Material, 99},
    /* kItemRay            */ {"Ray", ItemCategory::Material, 99},
    /* kItemTurtle         */ {"Turtle", ItemCategory::Material, 99},
    /* kItemCottage        */ {"Cottage", ItemCategory::Placeable, 9},
    /* kItemHut            */ {"Hut", ItemCategory::Placeable, 9},
    /* kItemManor          */ {"Manor", ItemCategory::Placeable, 9},
    /* kItemSnowman        */ {"Snowman", ItemCategory::Placeable, 99},
    /* kItemGateRight      */ {"Gate (Right)", ItemCategory::Placeable, 99},
    /* kItemRoof           */ {"Roof", ItemCategory::Placeable, 99},
    /* kItemPathDirt       */ {"Dirt Path", ItemCategory::Placeable, 99},
    /* kItemPathPlank      */ {"Plank Path", ItemCategory::Placeable, 99},
    /* kItemRail           */ {"Rail", ItemCategory::Placeable, 99},
    /* kItemRugLong        */ {"Rug (Long)", ItemCategory::Placeable, 99},
    /* kItemBed            */ {"Bed", ItemCategory::Placeable, 9},
    /* kItemWoodTable      */ {"Table", ItemCategory::Placeable, 99},
    /* kItemDresser        */ {"Dresser", ItemCategory::Placeable, 99},
    /* kItemStool          */ {"Stool", ItemCategory::Placeable, 99},
    /* kItemBench          */ {"Bench", ItemCategory::Placeable, 99},
    /* kItemHoe            */ {"Hoe", ItemCategory::Tool, 1},
    /* kItemWorkbench      */ {"Workbench", ItemCategory::Placeable, 9},
    /* kItemTrough         */ {"Feed Trough", ItemCategory::Placeable, 99},
    /* kItemHayBale        */ {"Hay Bale", ItemCategory::Placeable, 99},
    /* kItemWaterTray      */ {"Water Tray", ItemCategory::Placeable, 99},
    /* kItemBoat           */ {"Rowboat", ItemCategory::Placeable, 9},
    /* kItemPicnic         */ {"Picnic Set", ItemCategory::Placeable, 9},
    /* kItemPresent        */ {"Present", ItemCategory::Placeable, 99},
    /* kItemChestSilver    */ {"Silver Chest", ItemCategory::Placeable, 9},
    /* kItemChestGold      */ {"Golden Chest", ItemCategory::Placeable, 9},
    /* kItemClone          */ {"Clone Mirror", ItemCategory::Placeable, 1},
    /* kItemSunflowerSeed  */ {"Sunflower Seed", ItemCategory::Seed, 99},
    /* kItemSunflower      */ {"Sunflower", ItemCategory::Crop, 99},
};

} // namespace core
