// Generates tests/wall_cases.inc: the JS rule's output over EVERY cell of
// every scenario the user reviewed, as C arrays.
//
//   node tools/wall_lab/gen_cpp_cases.js
//
// This is how the C++ port (source/core/wall_autotile.cpp) is pinned to the
// lab: tests/test_wall_autotile.cpp replays every grid and requires the same
// role name at every cell, wall layer and overlay layer both - ~6000
// assertions. The JS rule already satisfies all 73 of the user's fixes and
// all 3005 keeps (tests/js/test_wall_rule.js), so C++ == JS means C++ ==
// what the user accepted.
//
// Regenerate whenever the rule changes in the lab (after re-verifying it
// against the golden data first).
"use strict";
const fs = require("fs");
const path = require("path");
const { loadRule } = require("../../tests/js/rule_harness.js");
const CASES = require("../../tests/js/wall_cases.json");

const api = loadRule();
const DEST = path.join(__dirname, "..", "..", "tests", "wall_cases.inc");

const lines = [];
lines.push("// GENERATED by tools/wall_lab/gen_cpp_cases.js - do not edit.");
lines.push("// The lab rule's output over every cell of every user-reviewed scenario.");
lines.push("// clang-format off");
lines.push("struct WallCase {");
lines.push("    const char* id;");
lines.push("    int w, h;");
lines.push("    const uint16_t* floors;  // packed (x << 8) | y");
lines.push("    int nFloors;");
lines.push("    const char* const* wall;     // w*h role names, \"\" on floor cells");
lines.push("    const char* const* overlay;  // w*h role names, \"\" where none");
lines.push("};");
lines.push("");

const q = s => JSON.stringify(s);
let n = 0;
const entries = [];
for (const r of CASES.reviewed) {
  const floors = r.floors.map(([x, y]) => (x << 8) | y);
  const wall = [], overlay = [];
  for (let y = 0; y < r.h; y++) {
    for (let x = 0; x < r.w; x++) {
      api.setup(r.w, r.h, r.floors);
      wall.push(api.roleAt(x, y, "wall") || "");
      api.setup(r.w, r.h, r.floors);
      overlay.push(api.roleAt(x, y, "overlay") || "");
    }
  }
  lines.push(`static const uint16_t kFloors_${n}[] = {${floors.join(",") || 0}};`);
  lines.push(`static const char* const kWall_${n}[] = {${wall.map(q).join(",")}};`);
  lines.push(`static const char* const kOv_${n}[] = {${overlay.map(q).join(",")}};`);
  entries.push(`    {${q(r.id)}, ${r.w}, ${r.h}, kFloors_${n}, ${r.floors.length}, kWall_${n}, kOv_${n}},`);
  n++;
}
lines.push("");
lines.push("static const WallCase kWallCases[] = {");
lines.push(...entries);
lines.push("};");
lines.push(`static const int kWallCaseCount = ${n};`);
lines.push("");

fs.writeFileSync(DEST, lines.join("\n"));
const cells = CASES.reviewed.reduce((a, r) => a + r.w * r.h * 2, 0);
console.log(`wrote ${DEST}: ${n} scenarios, ${cells} cell expectations`);
